<a href="https://colab.research.google.com/github/NiazG/ml_zoomcamp/blob/main/HW_week1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
from matplotlib import pyplot as plt
%matplotlib inline

**Question 1**
version of the pandas

In [3]:
pd.__version__

'1.5.3'

In [4]:
!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv

--2023-09-17 08:31:39--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.111.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1423529 (1.4M) [text/plain]
Saving to: ‘housing.csv.1’

housing.csv.1       100%[===================>]   1.36M  --.-KB/s    in 0.03s   

2023-09-17 08:31:39 (39.0 MB/s) - ‘housing.csv.1’ saved [1423529/1423529]



**Question 2**
number of columns

In [5]:
housing = pd.read_csv('housing.csv')

**Question 3**
columns with mising values

In [6]:
housing.isna().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

**Question 4**
unique values in column "ocean_proximity"

In [7]:
len(housing.ocean_proximity.unique())

5

**Question 5**
Average value of the 'median_house_value' for the houses near the bay

In [8]:
housing[housing.ocean_proximity == "NEAR BAY"].median_house_value.mean()

259212.31179039303

**Question 6**
Has the mean value changed after filling missing values?



In [9]:
housing.total_bedrooms.mean()

537.8705525375618

In [10]:
#filling the missing values with the mean
housing.total_bedrooms = housing.total_bedrooms.fillna(housing.total_bedrooms.mean())

In [11]:
housing.total_bedrooms.isna().sum()

0

In [12]:
housing.total_bedrooms.mean()

537.8705525375617

**Question 7**
Value of the last element of w

In [57]:
X = np.array(housing[housing.ocean_proximity == 'ISLAND'][['housing_median_age', 'total_rooms', 'total_bedrooms']])
X

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [58]:
XTX = X.T.dot(X)
XTX.shape

(3, 3)

In [59]:
IXTX = np.linalg.inv(XTX)
IXTX.shape

(3, 3)

In [60]:
y = np.array([950, 1300, 800, 1000, 1300])
y

array([ 950, 1300,  800, 1000, 1300])

In [69]:
w = IXTX.dot(X.T).dot(y)
w

array([23.12330961, -1.48124183,  5.69922946])

In [68]:
w[-1]

5.699229455065586